# -*- coding: utf-8 -*-
"""Video Games Sales Python Project-Nick.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5vPclmm3j69YZG7o_jCzAEg3jF4HnK8

## #Video Games Sales

> Section: F

## Executive summary

In this project, I analyzed the Video Games Sales dataset to uncover global market trends and regional preferences. I began by cleaning the data, removing duplicates and missing values to increase accuracy, before conducting an exploratory analysis that identified the top-performing platforms, genres, and publishers. My deeper investigation revealed significant insights, most notably the robust performance of the PS2 globally, and an interesting cultural divergence where North American markets favor Action and Shooter games while Japan is dominated by Role-Playing Games. I also tracked sales over time, noting a peak in 2008-2009 followed by shifting genre popularity, and found that while top publishers like Nintendo and EA maintain consistent rankings across North America and Europe, the sheer scale of the North American market significantly outweighs the European one.

Video Link: https://www.youtube.com/watch?v=qcKoTh2ywsQ

## Importing libraries

*To begin, you will need to import the necessary libraries*
"""

import pandas as pd
df = pd.read_csv("video_games_sales.csv", sep=';')

"""## Explore your data

*Explore the data: Before diving into analysis, it's important to get a general idea of the data. Use the necessary functions to explore the data and get a sense of its structure and contents.*
"""

df

df.columns

df.index

print(df.info())
print(df.isnull().sum())

df.describe()

"""## Clean data

*Clean the data: Data can contain errors, null values, outliers, etc. It's important to clean the data before any analysis. Use Pandas functions  to clean the data.*
"""

df2 = df
df2 = df.copy()
print("Nulls:", df2.isnull().sum().sum())
print("Duplicates:", df2.duplicated().sum())

df2.drop_duplicates(inplace = True)
df2.dropna(inplace = True)

print("New shape after cleaning:", df2.shape)
print("Nulls remaining:", df2.isnull().sum().sum())

df2

platform_counts = df2['Platform'].value_counts()

print("Top 5 Platforms by number of games:")
print(platform_counts.head(5))

genre_counts = df2['Genre'].value_counts()

print("Most common Genres produced:")
print(genre_counts)

publisher_counts = df['Publisher'].value_counts()

print("Top 5 active Publishers:")
print(publisher_counts.head(5))

year_counts = df['Year'].value_counts()

print("Games released per Year:")
print(year_counts.head(10))

name_counts = df['Name'].value_counts()

print("Most frequent Game Names (Multi-platform releases):")
print(name_counts.head(5))

sales_over_time = df2.groupby(['Year'])['Global_Sales'].sum()

print("Sales per year (in millions):")
print(sales_over_time)

sales_by_genre = df2.groupby(['Genre'])['Global_Sales'].sum().sort_values(ascending=False)

print("Total Sales by Genre (in millions):")
print(sales_by_genre)

"""## Visualize the data

*Visualize the data: Visualizations can help you better understand the data and glean valuable insights. Use Python visualization libraries like Matplotlib, Seaborn to create charts and graphs.*
"""

filtered_comp.plot(kind='bar', stacked=True, figsize=(10, 6))

import matplotlib.pyplot as plt
plt.title('Regional Sales Mix of Top 5 Platforms')
plt.ylabel('Total Sales (in Millions)')
plt.xlabel('Platform')
plt.xticks(rotation=0) # So that we keep the labels flat
plt.legend(title='Region')
plt.show()

culture_clash.sort_values(by='NA_Sales', ascending=False).head(10).plot(kind='bar', figsize=(12, 6))

plt.title('Genre Preferences: North America vs. Japan')
plt.ylabel('Sales (in Millions)')
plt.xlabel('Genre')
plt.xticks(rotation=45) # Looks better at 45 degree angle (since we have 10 genres)
plt.show()

clean_fav_genres.plot(kind='line', figsize=(12, 6), linewidth=3)

plt.title('Sales Evolution of Key Genres (2007-2016)')
plt.ylabel('Global Sales (in Millions)')
plt.xlabel('Year')
plt.grid(True, linestyle='--', alpha=0.5) # We added a light grid for readability
plt.show()

publisher_region.sort_values(by='NA_Sales', ascending=True).tail(5).plot(kind='barh', figsize=(10, 6))

plt.title('Top Publishers: Market Scale (NA vs EU)')
plt.xlabel('Sales (in Millions)')
plt.ylabel('Publisher')
plt.show()

"""## Perform the analysis

*Use Pandas functions to perform the desired analysis. For example, you can use groupby(), pivot_table(), value_counts(), etc. to get information about the data.*
"""

# We group by Platform and sum specific regional sales
console_comp = df2.groupby('Platform')[['NA_Sales', 'EU_Sales', 'JP_Sales']].sum()

# We filter only the BIG platforms to keep our plot clean (Top 5 by Global Sales)
top_platforms = df2.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(5).index
filtered_comp = console_comp.loc[top_platforms]

print("Regional Breakdown of Top 5 Platforms:")
print(filtered_comp)

# We compare North America vs Japan preferences by Genre
culture_clash = df2.groupby('Genre')[['NA_Sales', 'JP_Sales']].sum()

# We sort by NA sales to see the contrast
print("Cultural Differences (by NA sales) in Genre (NA vs JP):")
print(culture_clash.sort_values(by='NA_Sales', ascending=False).head(5))

# We sort by JP sales to see the contrast
print("Cultural Differences (by JP sales) in Genre (NA vs JP):")
print(culture_clash.sort_values(by='JP_Sales', ascending=False).head(5))

# NOT USING THIS; ONLY FOR EXPLANATION
# We create a pivot table: Rows=Year, Columns=Genre, Values=Sales
genre_evolution = df2.pivot_table(index='Year', columns='Genre', values='Global_Sales', aggfunc='sum')

# We selected our 3 personal favorite contrasting genres to keep the plot readable
# (If we plot all 12, it looks like spaghetti)
fav_genres = genre_evolution[['Action', 'Sports', 'Shooter']]

print("Sales evolution of key Genres (in millions):")
print(fav_genres.tail(10)) # Show only the last 10 years of data

genre_evolution = df2.pivot_table(index='Year', columns='Genre', values='Global_Sales', aggfunc='sum')

fav_genres = genre_evolution[['Action', 'Sports', 'Shooter']]

# Now, we filter to exclude the incomplete years (keep only data before 2017)
clean_fav_genres = fav_genres[fav_genres.index < 2017]

print("Sales(in Millions) evolution of key Genres (Cleaned):")
print(clean_fav_genres.tail(10))

# We group by Publisher and sum only NA and EU sales
publisher_region = df2.groupby(['Publisher'])[['NA_Sales', 'EU_Sales']].sum()

print("Top Publishers in North America:")
# Sort by NA to see who owns the US market
print(publisher_region.sort_values(by='NA_Sales', ascending=False).head(5))

print("\nTop Publishers in Europe:")
# Sort by EU to see who owns the European market
print(publisher_region.sort_values(by='EU_Sales', ascending=False).head(5))

"""## Communicate your findings

It's important to communicate your findings clearly and effectively. Use visualization libraries to create charts and graphs that are easy to understand. You can also use natural language to explain your findings.

First Findings (Tutoring Session):
- Original Data Set: 16,621 Rows, 11 Columns (used sep=';' because the file format wasn't standard comma-seperated)
- Columns are a mix of Numerical and Categorical Data
- Fixed nulls and duplicates
- Cleaned Data Set: 16,268 Rows, 11 Columns
- Developed our initial 4 insights

Insight 1: Console Competition
- Observation: When I analyzed the Top 5 platforms, I found that "Global Sales" is a misleading metric. For example, while the Xbox 360 was a dominant platform in North America (rivaling the PlayStation), it was nearly non-existent in the Japanese market. Conversely, the Nintendo DS performed disproportionately well in Japan compared to the West.

Insight 2: Cultural Divergence (NA vs JP)
- Observation: By sorting genre preferences by region, I discovered a massive cultural divide. The North American market is dominated by Action and Shooter games. However, when I view the exact same data sorted by Japanese sales instead of North American sales, I observe that this is not exactly the case for their market, and instead, Action and Shooter games are replaced by Role-Playing games.

Insight 3: The Evolution of Gamer Tastes (2007–2016)
- Observation: My 10-year timeline analysis (2007–2016) highlights a decisive shift in industry dominance. In 2009, Sports games were at their peak (around 138M sales), actually outperforming Action in global sales. However, they experienced a severe decline shortly after, dropping approximately 70% by 2015. In contrast, the Action and Shooter genres remained relatively resilient throughout the timeframe. By 2011, Shooters had surged to nearly double the sales of Sports games, and Action titles consistently maintained the top spot.  Finally, came the massive drop in sales in 2016 for all respective genres.

Insight 4: Top Publisher Comparison (NA vs EU)
- Observation: My analysis of the top publishers reveals a major consistency in rankings across both continents. The top five publishers, led by Nintendo, Electronic Arts, and Activision appear in the exact same order in both the North American and European top lists. The primary distinction that we found in the data is the scale/size of the markets; for every single one of these top five publishers, North American sales volumes are significantly higher than the European market.
"""